### ISSUE TITLE
queries_not_using_index - ignore reports with "No matching min/max row" / "Select tables optimized away"

### ISSUE THREAD

**Issue by macbre** [macbre/index-digest#210]
```yaml
- type: queries_not_using_index
  table: null
  message: '"SELECT max(foo.last_..." query did not
    make use of any index'
  context:
    query: SELECT max(foo.last_successful_generation_end_time) AS max_1  FROM foo
    explain_extra: No matching min/max row
    explain_rows: null
    explain_filtered: null
    explain_possible_keys: null
```

and

```yaml
- type: queries_not_using_index
  table: null
  message: '"SELECT max(foo.last_successful_generation_..." query did not make use of any index'
  context:
    query: SELECT max(foo.last_successful_generation_end_time) AS max_1  FROM foo
    explain_extra: Select tables optimized away
    explain_rows: null
    explain_filtered: null
    explain_possible_keys: null
```

> The query contained only aggregate functions (MIN(), MAX()) that were all resolved using an index, or COUNT(*) for MyISAM, and no GROUP BY clause. The optimizer determined that only one row should be returned.
