### ISSUE TITLE
Add YAML results formatter

### ISSUE THREAD

**Issue by macbre** [macbre/index-digest#68]
See #35 

```yaml
---
meta:
  version: index-digest v0.1.0
  database_name: index_digest
  database_host: debian
  database_version: MySQL v5.7.20
reports:
- type: redundant_indices
  table: 0004_id_foo
  message: '"idx" index can be removed as redundant (covered by "PRIMARY")'
  context:
    redundant: !index 'UNIQUE KEY idx (id, foo)'
    covered_by: !index 'PRIMARY KEY (id, foo)'
    schema: "CREATE TABLE `0004_id_foo` (\n  `id` int(9) NOT NULL AUTO_INCREMENT,\n\
      \  `foo` varbinary(16) NOT NULL DEFAULT '',\n  PRIMARY KEY (`id`,`foo`),\n \
      \ UNIQUE KEY `idx` (`id`,`foo`)\n) ENGINE=InnoDB DEFAULT CHARSET=latin1"
    table_data_size_mb: 0.015625
    table_index_size_mb: 0.015625
- ...
- type: queries_using_full_table_scan
  table: 0002_not_used_indices
  message: '"select * from 0002_not_used_indices where bar = ''f..." query triggered
    full table scan'
  context:
    query: select * from 0002_not_used_indices where bar = 'foo'
    explain_rows: 3
...
```
